### ISSUE TITLE
Error when aggregating on composite key

### ISSUE THREAD

**Issue by booboothefool** [tandg-digital/objection-filter#14]
For example if I did:
```
           $aggregations: [{
               type: 'count',
               alias: 'numberOfOrders',
               relation: 'orders',
           }],
```
and orders happens to have a composite key consisting of ['key1', 'key2'] then I get error:
```
column orders.key1,key2 does not exist
```

**Comment by jeff3yan** [comment]
At the moment, aggregating on tables with composite keys isn't supported. I'll take a look shortly to determine the ease of adding this feature.

There have been pull requests in the past to add composite key support to other features, so I'd definitely look into it eventually.

**Comment by jeff3yan** [comment]
I've replicated the issue and resolved it in the [develop](https://github.com/tandg-digital/objection-filter/tree/develop) branch. I might add more tests later on to cover it then eventually publish.
