### ISSUE TITLE
Model.query is not a function

### ISSUE THREAD

**Issue by iboriska** [tandg-digital/objection-filter#2]
I found your plugin in an answer to this question [https://github.com/strongloop/loopback/issues/517](https://github.com/strongloop/loopback/issues/517).
I tried to use it but it says that Model.query is not a function and indeed there is no such method when I debug the code.
Maybe I do something wrong.

My loopback version is 2.38.3

**Comment by jeff3yan** [comment]
In that thread I was discussing the downsides of the Loopback ORM and how that has resulted in moving to the objection.js ORM and creating the objection-filter module. That is the main reason I created the issue [here](https://github.com/strongloop/loopback/issues/3407).
