### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [tandg-digital/objection-filter#24]
This npm package needs a TypeScript types declaration file so that developers who enjoy writing with TS can use it with this package and have a better development experience. Would you like me to write one?

**Comment by jeff3yan** [comment]
Sure, that would be really appreciated :+1: . Feel free to submit a pull request for review and I'll take a look.

**Comment by geopic** [comment]
Will get started on it soon @jeff3yan , thanks
