### ISSUE TITLE
Mystery variable 'builder'

### ISSUE THREAD

**Issue by tubular400** [tandg-digital/objection-filter#25]
Where does the variable 'builder' come from in the function 'createOnAggBuild' here:

  https://github.com/tandg-digital/objection-filter/blob/v2.3.1/doc/AGGREGATIONS.md#aggregation-model-hooks

**Comment by jeff3yan** [comment]
That's an error in the documentation, it should be `return Model.query().where({ tenantId })`. I'll resolve that soon, thanks for pointing that out.
