### ISSUE TITLE
Using untrusted data as filter: secure?

### ISSUE THREAD

**Issue by tubular400** [tandg-digital/objection-filter#26]
The sample code at https://github.com/tandg-digital/objection-filter/tree/v2.3.1#usage suggests using untrusted data from `req.query.filter`.  Similar examples exist elsewhere in the docs:

* https://github.com/tandg-digital/objection-filter/blob/v2.3.1/doc/AGGREGATIONS.md#another-method-of-aggregation-filtering
* https://github.com/tandg-digital/objection-filter/blob/v2.3.1/doc/AGGREGATIONS.md#aggregation-model-hooks ("Aggregation model hooks" section)

Can you give any assurance that it is safe to pass untrusted data to `objection-filter`?

**Comment by jeff3yan** [comment]
The original intention of objection-filter was the ability to pass in arbitrary filters, such as with [graphql](https://graphql.org/) or larger frameworks like [loopback](https://loopback.io/).

However anywhere where you expose such an interface publically should have some checks prior to entering the query builders. These could be limiting the number of returned records, the _depth_ of eager data queries or other cost analysis depending on your data.

[This](https://blog.apollographql.com/securing-your-graphql-api-from-malicious-queries-16130a324a6b) is a good article describing some very similar details for graphql APIs which would apply similarly here.
