### ISSUE TITLE
SQL with syntax error generated

### ISSUE THREAD

**Issue by tubular400** [tandg-digital/objection-filter#27]
I added`objection-filter` to an application.  Then I tested it, and found a filter that causes SQL with a syntax error to be generated.

Here is the filter:

```json
{
  "fields": ["uuid", "key"],
  "eager": { "$where": { "cast(uuid AS text)": { "$like": "%a%a%a%" } } }
}
```

Here is some output from the application (produced because Knex's `debug` option is `true`):

```javascript
{                                                                                     
  method: 'select',
  options: {},                                                                        
  timeout: false,
  cancelOnTimeout: false,                                                             
  bindings: [ '%a%a%a%' ],                                                            
  __knexQueryUid: 'c4b6d571-4db4-11ea-9425-f50ad35c69fa',                             
  sql: 'select "customizations"."uuid", "customizations"."key" from "customizations" wh
ere ("customizations"."cast(uuid" as "text)" like ?)'                                 
}
```

Here is some more output from the application, probably generated by the [`db-errors`](https://www.npmjs.com/package/db-errors) module:

```text
DBError: select "customizations"."uuid", "customizations"."key" from "customizations" where ("customizations"."cast(uuid" as "text)" like $1) - syntax error at or near "as"
```

To summarize: SQL with a syntax error is being generated, and it is probably the fault of `objection-filter`.

This problem makes me think that `objection-filter` is likely to have SQL injection bugs (though I haven't tried to find any).

**Comment by tubular400** [comment]
Various software versions:

* Node.js: 12.13.0
* Objection: 2.1.2
* objection-filter: 2.3.1

And here is the interesting output from the command `psql -A -c "SELECT version()"`

```text
PostgreSQL 11.6 (Debian 11.6-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
```

**Comment by jeff3yan** [comment]
This particular query would go into this part of `objection-filter`:
https://github.com/tandg-digital/objection-filter/blob/master/src/lib/utils.js#L39

Since objection.js essentially [provides many of the same knex interfaces](https://vincit.github.io/objection.js/api/query-builder/find-methods.html#where), it would eventually reach here:
https://github.com/knex/knex/blob/master/lib/query/builder.js#L267

The knex `where()` statement is typically parameterized, however I'll spend some time looking at this particular issue. SQL injection hasn't been logged previously as an issue there (compared to using the `whereRaw()` function.

**Comment by tubular400** [comment]
> I'll spend some time looking at this particular issue

Thanks.

**Comment by jeff3yan** [comment]
On second glance, everything is working as expected. The main issue is because of the expression `cast(uuid AS text)`, which is treated as a column identifier.

This identifier simply gets passed to knex.js and eventually ends up being wrapped in double-quotes.

**Comment by tubular400** [comment]
Invalid SQL is being generated, so there must be a bug somewhere.  If I correctly understand your last comment, then I must conclude that the bug is in Knex.

**Comment by tubular400** [comment]
The bug is in Knex, alright.  I wrote this little program:

```javascript
const knexMod = require('knex');

main().catch(console.error);

async function main() {
  const knex = knexMod({
    client: 'pg',
    connection: process.env.DATABASE_URL,
    debug: true,
  });

  try {
    await knex('customizations').where('cast(uuid AS text)', 'like', '%a%a%a%');      
  } finally {
    knex.destroy();
  }
}
```

When I run it, it generates SQL with a syntax error, as is clear from its output:

```text
{
  method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ '%a%a%a%' ],
  __knexQueryUid: '5793b380-4e4c-11ea-a5d1-c7998438fcce',
  sql: 'select * from "customizations" where "cast(uuid" as "text)" like ?'
}
error: syntax error at or near "as"
    at Connection.parseE (/tmp/syntax-error-1/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/tmp/syntax-error-1/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/tmp/syntax-error-1/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '50',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1134',
  routine: 'scanner_yyerror'
}
```

**Comment by globsecure** [comment]
This is not an error but protection, which does not let you use SQL commands without using the RAW function:

http://knexjs.org/#Raw
http://knexjs.org/#Schema-raw

**Comment by jeff3yan** [comment]
It's definitely a problem since knex explicitly checks for column aliasing when wrapping column identifiers. Maybe there could be slightly different behavior for column wrapping based on the query context.

I'll close this issue though since it's an existing issue with knex.
