### ISSUE TITLE
Deprecated method used (Objection method 'eager')

### ISSUE THREAD

**Issue by tubular400** [tandg-digital/objection-filter#28]
I added `objection-filter` to an application and ran a query against it.  The query worked, but the application printed the following message:

> `QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` method instead. `eager` method will be removed in 3.0

The application is using Objection 2.1.2.

**Comment by globsecure** [comment]
I believe this is a valid adjustment

**Comment by jeff3yan** [comment]
I'll take a look at this soon, I'll go through and audit the code base for the latest objection version.

**Comment by jeff3yan** [comment]
This has been fixed in the develop branch, and will be merged to master shortly.
