### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by alexisohayon** [tandg-digital/objection-filter#3]
Hi! 
This lib is really nice but I liked the way objection works with paging, especially to get the total count of a query. How can I do that with objection-filter? Thanks!

**Comment by jeff3yan** [comment]
That's definitely something I've been thinking of adding, but not sure if I have the time in the near future.

The object returned by the `build()` function is a standard objection builder, and you may be able to extract that and run a count query + the base query.

Take a look at the [toSql](http://vincit.github.io/objection.js/#tosql) function but either way it will require 2 queries.

**Comment by alexisohayon** [comment]
Nice! Do you know how to do such a thing?

**Comment by alexisohayon** [comment]
Allright, I think I found a working solution by digging the code of objection a bit: by chaining with .range() after the build(), you can set start and end and get the total count also :)
I also found this:
```js
page(page, pageSize) {
 return this.range(page * pageSize, (page + 1) * pageSize - 1);
}
```
With this, it should be easy to get the results by page.

**Comment by jeff3yan** [comment]
I see what you mean, that's sort of possible on the current objection filter at the moment using range & offset, but you'll need to manage the page size yourself.

I thought you were trying to find the total number of pages for a particular query. Great to hear you solved your problem though.
