### ISSUE TITLE
[Question]Return QueryBuilder to chain

### ISSUE THREAD

**Issue by ellisium** [tandg-digital/objection-filter#31]
Hello,

Thank you for this plugin. I wonder if it's possible to chain the result with a method like "patchAndFetch" or "update"?

Regards

**Comment by jeff3yan** [comment]
The result of `build()` returns a QueryBuilder, so you'd be able to chain any standard knex/objection function onto it (eg `whereNull()` or `first()`).

From my understanding patchAndFetch is an instance based function, so you wouldn't be able to chain it directly.

You should be able to do something like:
```typescript
const people = await buildFilter(Person)
  .build({ where: { id: 1 }});

const person = people[0];
await person.$query()
  .patchAndFetch({ firstName: 'New Name' });
```

**Comment by ellisium** [comment]
Ok thank you, it work as expected. 
However any way to perform an update on all results returned by the filter without to run forEach loop?

**Comment by jeff3yan** [comment]
If your result set is an array of objects with some ids, you could use the bulk update function from objection/knex.

```typescript
const people = await buildFilter(Person)
  .build({ where: { isVerified: true }});

const updatedPeople = await Person.query()
  .update({ someAttribute: 123 })
  .whereIn('id', people.map(person => person.id));
```

Objection.js (and similarly knex) are mostly interfaces through to standard SQL. Anything you'd be able to do in SQL (such as a bulk update) you'll be able to do with objection.js
