### ISSUE TITLE
$or is not behaving correctly when used before properties

### ISSUE THREAD

**Issue by Rfrixy** [tandg-digital/objection-filter#35]
Followed the docs to make a query along the lines of :
```
eager: {
$where: {
 $or: [{x.y: { $in: [1,2,3]}}, {a.b: { $in: [1,2,3]}}]
}}
```

and the or query doesn't work, it's performing an 'and' comparison instead.

**Comment by jeff3yan** [comment]
I've just tested this out locally with a very similar query in one of the test cases, and there was no issue there.

Would you be able to let me know the SQL generated by this filter?
