### ISSUE TITLE
Support for FieldExpressions/JSONB

### ISSUE THREAD

**Issue by elby22** [tandg-digital/objection-filter#36]
Would it be feasible to add support for JSONB (postgres) queries using [FieldExpressions](https://vincit.github.io/objection.js/api/types/#type-fieldexpression)? The `<tableName>.jsonCol:property` syntax does not seem to work with the filter builder, and it is rather difficult to implement using custom operators.

**Comment by jeff3yan** [comment]
I'd need to investigate a bit more, since I'm not too familiar with the postgres jsonb operators in depth. Was there any specific type of filter that you were after?

**Comment by jeff3yan** [comment]
One thing you could look at is simply using the postgres jsonb addressing syntax eg `->>`

For example, here's something like a JSONB-EQUALS operator:

```js
const options = {
  operators: {
    $jequals: (property, operand, builder) => {
      const [ attribute, value ] = operand;
      return builder.whereRaw('?? ->> ? = ?', [property, attribute, value])
    }
  }
};

buildFilter(Person, null, options)
  .build({
    eager: {
      $where: {
        payload: { $jequals: [ 'name', 'john' ] }
      }
    }
  })
```

I'm just using an array to represent the attribute/value tuple here, but you could use an object or whatever suits you.

**Comment by elby22** [comment]
Thanks for the quick reply @jeff3yan. I had considered that and had some limited success, but I wanted to take advantage of the existing operators. It seems that Objection will take care of the raw JSONB operators if you use the `ref()` function and the syntax for the FieldExpressions. The strategy I'm going to try tomorrow is to parse the FieldExpressions from the filter specifically using that colon syntax mentioned above, and see if I can persist the reference throughout the graph. Will give updates.

**Comment by elby22** [comment]
Hey @jeff3yan, I have a draft PR #37 that I'm working on to solve this issue. Would you be willing to give it a look and provide some feedback? 
My approach is to wrap any property which resembles a FieldExpression as a ReferenceBuilder and cast based on the operand type. The only issue I'm running into is the `fullyQualifiedProperty` from `sliceRelation`, which uses similar syntax. One solution is to use the ReferenceBuilder and add the relation name as is done in [JSON Queries Objection.js Recipie](https://vincit.github.io/objection.js/recipes/json-queries.html).

**Comment by jeff3yan** [comment]
Hey thanks for the PR, I'll definitely take a look in the next few days.

I see the issue with the ambiguous property names though. My main concern would be like you said, the interaction with Objection's own syntax for referencing related tables. I'll take a closer look later though.

**Comment by jeff3yan** [comment]
Has there been any update on this PR @elby22? Based on the PR the logic looks sound, but it would be worth adding a couple of test cases as I mentioned there.

**Comment by elby22** [comment]
@jeff3yan I have added more tests and array indexing to the PR. Please have a look when you get a chance.

**Comment by jeff3yan** [comment]
This has been merged into master now.
