### ISSUE TITLE
Merging filters

### ISSUE THREAD

**Issue by vkruoso** [tandg-digital/objection-filter#45]
Is there any straightforward and/or recommended way of merging two or more filters to be used in the same query?

The use case is that I have a lot of filters, I must show each filter total count (that can be executed as one query per filter), but I also need the overall count, as a merge of all queries. The result is different from the sum of all queries counts because there might be an overlap of results from one filter to another.

I tried to use the build function multiple times, but as it returns a `QueryBuilder`, I can't chain it. Maybe objection has a way to do it or it could be a feature of this plugin?

**Comment by jeff3yan** [comment]
From what I understand, what you're trying to do is:

* You want to run multiple queries, each with it's own different filter
* You want to combine all the filters together, and get the results from that

Were you just trying to get the count for each of these queries? Or get the entire result set?

A straightforward way to implement this would be to use multiple filters, then another filter which combines them using a logical `AND`.

However either way you'd have to run this query multiple times. For example:

```typescript
const filterWhere1 = { "firstName": "John" };
const filterWhere2 = { "country": "United States" };

const result1 = await buildFilter(Customer)
  .build({ where: filterWhere1 });
const result2 = await buildFilter(Customer)
  .build({ where: filterWhere2 });

const mergedResult = await buildFilter(Customer)
  .build({ where: { $and: [ filterWhere1, filterWhere2 ] } });
```

Does this answer your question? Cheers

**Comment by vkruoso** [comment]
Hi @jeff3yan! Thanks for the detailed answer. Got this working using the `$or` operator in this case, something like
`.build({ eager: { $where: { $or: filters } } })`.
