### ISSUE TITLE
Should eager load use left join instead of inner join?

### ISSUE THREAD

**Issue by FrazCake** [tandg-digital/objection-filter#47]
Hi, I'm facing an issue that occurs whenever a related table is eager loaded. 
I use the following eager schema:
```
{
  '$where': { 'machine.nome': {} },          //  I need this to apply an 'orderByRaw' on this field
  machine: {},
}
```
I noticed that, even if I don't apply any filter, all entries having null as value in the linking attribute are not retrieved from the db.
This is the interesting part of the generated query:

```
select `semilavorati`.* from `semilavorati` inner join `macchine` as `machine` on `machine`.`idmacchina` =  

`semilavorati`.`macchina` order by cast (coalesce(`machine`.`nome`, "") as unsigned) asc, `machine`.`nome`
```

As you can see the query uses an inner join. Maybe a left join could fix this issue.
Of the three occurrences of .joinRelated that I found in FilterQueryBuilder.js I replaced this one

```
if (isOnlyJoiningToBelongsTo) {
        // If there are only belongsTo or hasOne relations, then filter on the main query
        applyLogicalExpression(filter, builder, false, getFullyQualifiedName);
        const joinRelation = ExpressionBuilder_1.createRelationExpression(propertiesSet);
        ------> builder.joinRelated(joinRelation); <-------
        return builder;
    }
```

with this one
```
builder.leftJoinRelated 
```
and it seems to work fine.

I hope that what I wrote makes some sense.
Any help would be appreciated.

**Comment by jeff3yan** [comment]
This looks pretty reasonable, let me test it on some scenarios and I'll get back to you on it.

**Comment by jeff3yan** [comment]
Ok so the main reason this is happening is due to the `$where` condition that you mentioned earlier, eg:

> I noticed that, even if I don't apply any filter, all entries having null as value in the linking attribute are not retrieved from the db.

This was originally implemented based on the assumption that some filter would always be applied if a `$where` was used.

For your use case, I'd probably suggest replacing the `$where` with your own custom `leftJoinRelated` and `orderByRaw` since it's quite specific.

However off the top of my head I don't see any downside in replacing that inner join with a left join in the code base, but I'd probably want to run through all the test cases first.

**Comment by elby22** [comment]
@jeff3yan I've also run into this issue and I was thinking through the implications of using a left join instead. I havn't come up with a reason not to. The inner join essentially breaks how `$or` should work, in that in the inner join implies AND on the relation. I'm happy to make a PR and update tests if you think this is the right move.

**Comment by jeff3yan** [comment]
@elby22 that sounds reasonable, if you could add a test to capture this scenario that would be great.

**Comment by jeff3yan** [comment]
@elby22 @FrazCake I've added some test cases to this and fixed the logic. I'll be publishing this update to NPM in the near future.

**Comment by emily-malone** [comment]
@jeff3yan any update on when you might publish to NPM?

**Comment by jeff3yan** [comment]
@emily-malone this has been published to NPM now.
