### ISSUE TITLE
ilike?

### ISSUE THREAD

**Issue by honestserpent** [tandg-digital/objection-filter#5]
This module is awesome, but I think it lacks the "ilike" operator that works in an insensitive way. Maybe it would be worth?

**Comment by jeff3yan** [comment]
Unfortunately `ilike` isn't part of the standard knex operator set, so any addition I make may need different implementations depending on the sql dialect.

It might be easier for me to add some extensibility to the operators. You could then potentially add your own operators which would be interpreted with any standard `knex` functions.

**Comment by honestserpent** [comment]
That would be really cool. I just noticed that it is not part of standard knex.
So I'm wondering. How do someone even implements case-insensitive filtering in knex?

**Comment by jeff3yan** [comment]
You'd have to do something like:
```
await Model
  .query()
  .whereRaw('LOWER("myColumnName") ILIKE ?', ['abcd']);
```

This is discussed in some more detail [here](https://github.com/tgriesser/knex/issues/233).

**Comment by honestserpent** [comment]
But how would you integrate your module with that? I mean, what if I want to express a filter like:

`/people?filter={"where": {"first_name": {"ILIKE": "John%"}, "age": {"$gt": 21}}}`

to search for all the people that have a name starting with `John` (and I want the search to be insensitive), and with an `age >21`?

Could you please give me a simple complete example of something like this?

**Comment by jeff3yan** [comment]
Unfortunately this won't be a trivial addition, as the `ILIKE` operator exists in some dialects (e.g. postgres) but not in others. I'll have a think about adding extensible operators though.

Maybe something like:

```
const options = {
  operators: {
    $ilike: (property, operand, builder) => builder.where(property, 'ilike', operand)
  }
};
buildFilter(Model, trx, options)
```

**Comment by honestserpent** [comment]
Mmmm that way you would have to call it every time you want to use it. Wouldn't it be better if you could set your custom operators one time, in a set up phase?

**Comment by jeff3yan** [comment]
It would definitely be implemented as an options set, e.g. in the above example, the `$ilike` operator would be called each time an `$ilike` was encountered in the filter query object.

**Comment by jeff3yan** [comment]
I've updated the master branch with the custom operators functionality. It should work pretty much like I described above.

I'm working on a _medium_ sized refactor of the filter expression parser to allow for nested logic statements from #4 . However that doesn't seem like it'll affect the custom operators at all.
