### ISSUE TITLE
Aggregations can cause select statement collisions with relations

### ISSUE THREAD

**Issue by elby22** [tandg-digital/objection-filter#51]
It seems like filters with some relation expressions and a sorted aggregation can cause an overload in the returned columns. Given the following filter on the Movie model from the test environment, the name is overwritten by the category name. I've noticed this in my use of the library when the model instance was including fields from related tables.
```typescript
{
	eager: {
		$aggregations: [
			{
				type: 'count',
				relation: 'version',
				field: 'version',
				alias: 'versionCount',
			}
		],
		$where: {
			$and: {
				name: 'M12',
				'category.name': 'C08'
			}

		},
		category: true,
		version: true
	},
	order: 'versionCount desc'
}
```
I suspect that this is being caused by this line and its replacing the select statement generated by the Objection Model's QueryBuilder:
FilterQueryBuilder.ts line 298
```typescript
  // Finally, build the base query
  builder.from(fullQuery.as(Model.tableName));
```

I'm adding a PR with a failing test case as an example.

**Comment by jeff3yan** [comment]
Great, thanks for adding the failing test case on the PR. I'll take a look at this soon.

**Comment by jeff3yan** [comment]
Looks like this bug is more related to the fact that every column is selected on all joins, rather than just the root model.

It also can be replicated with this simpler test case:
```
it('should not cause field collisions in select statement', async () => {
  const query = buildFilter(Movie, null);
  const result = await query
    .build({
      eager: {
        $where: {
          $and: {
            name: 'M12',
            'category.name': 'C08'
          },
        },
        category: true
      }
    });

  const movie = result[0];

  expect(movie.name).to.equal('M12');
  expect(movie.category.name).to.equal('C08');
});
```

I'll probably implement the fix for this, and use this simpler test case to better isolate the issue.

**Comment by elby22** [comment]
Thanks @jeff3yan. I wanted to make sure that any `fields` passed to the filter were respected too, so I didn't try to implement a fix quite yet. Please let me know if there is anything else I can help with.
