### ISSUE TITLE
applyFields doesn't seem work correctly

### ISSUE THREAD

**Issue by artuuro** [tandg-digital/objection-filter#57]
Happens whenever I use similar query:
`{
    "eager": {
        "account": {
            "user": {}
        }
    },
    "fields": [
        "id",
        "account.name",
        "account.user.email"
    ]
}`

**Expected output:**
`{
    "results": [
        {
            "id": "xxxx",
            "account": {
                "name": "value",
                "user": {
                    "email": "name@tld"
                }
            }
        }
    ]
}`

**Output received:**
`{
    "results": [
        {
            "id": "xxxx",
            "created": "2020-01-01",
            "updated": "2020-01-01",
            "jsondata": {
                "key": "value"
            },
            "account": {
                "name": "value",
                "user": {
                    "email": "name@tld"
                }
            }
        }
    ]
}`

**Explanation of issue:** 
When no relation columns are selected it selects the correctly chosen columns as supposed, when I include related columns it will select completely all fields from the parent model and selected fields from childs, should be both the same in this case or am I missing something here?

**Comment by jeff3yan** [comment]
I'll have a look at this today, I see what you mean but I forget exactly how the logic works for this scenario.
