### ISSUE TITLE
Many to many filter

### ISSUE THREAD

**Issue by thisiskalnins** [tandg-digital/objection-filter#58]
Hello.

Is it possible to filter data based on m2m relation extra fields in pivot table?

**Comment by jeff3yan** [comment]
This won't be possible in a straightforward way I think.

I know there's methods like this (eg redefining some of the join tables as another relation):
https://github.com/Vincit/objection.js/issues/1356

**Comment by thisiskalnins** [comment]
Thank you for the answer.

I thought so. I found a workaround on this by defining m2m relation's pivot table as hasMany relation. Now i can filter by "extra" fields.
