### ISSUE TITLE
Transaction support?

### ISSUE THREAD

**Issue by honestserpent** [tandg-digital/objection-filter#6]
It looks like transactions are not supported.  It is extremely useful to be able to query models in a transaction.

I gave a quick look at the source code. Maybe it is not that hard to introduce transaction support.

const { buildFilter } = require('objection-filter');
const { Customer } = require('./models');

in **index.js**:

```
app.get('/Customers', function(req, res, next) {
  buildFilter(Customer, TRANSACTION_OBJ)
    .build(JSON.parse(req.query.filter))
    .then(customers => res.send(customers))
    .catch(next);
});
```

in **FilterQueryBuilder.js**:
```
constructor(Model, TRANSACTION) {
    this.Model = Model;
    this._builder = Model.query();
   if(TRANSACTION)
      this._builder.transacting(TRANSACTION);
  }
```

and probably that's it. What do you think?

**Comment by jeff3yan** [comment]
That was an easy add, so I've added transaction support. Must have crossed my mind during initial development.

**Comment by honestserpent** [comment]
Is it gonna be pushed to the master branch?

**Comment by jeff3yan** [comment]
Should already be on there,

**Comment by honestserpent** [comment]
oh, sorry, for some reason I didn't see "last update 5 minutes ago". LOL.

**Comment by honestserpent** [comment]
Sorry, I think something is missing in `/lib/index.js`

```
const FilterQueryBuilder = require('./lib/FilterQueryBuilder');

module.exports = {
  buildFilter: function (modelClass, TRANSACTION_OBJ) {
    return new FilterQueryBuilder(modelClass, TRANSACTION_OBJ);
  },
  FilterQueryBuilder: FilterQueryBuilder,
  sliceRelation: require('./lib/utils').sliceRelation,
  createRelationExpression: require('./lib/ExpressionBuilder').createRelationExpression
};
```

**Comment by jeff3yan** [comment]
Oops forgot about that, added.
