### ISSUE TITLE
User should be able to provide custom builder

### ISSUE THREAD

**Issue by efraimrodrigues** [tandg-digital/objection-filter#60]
Let's say Person entity has a modifier that introduces a new column. User should probably be able to filter Person by this new column.

```javascript
class Person extends objection.Model {
    static get tableName() {
      return 'Person';
    }

    static get modifiers() {
      return {
        withBirthYear(builder) {
          const currentYear = new Date().getFullYear();
          const personWithBirthYearQuery = Person.query().withGraphFetched("movies").select([
            "Person.id", 
            raw(`${currentYear} - age`).as("birthYear"),
          ]);
          builder.from(raw("(??)", personWithBirthYearQuery).as("Person"));
        },
      };
    }
}
```

I'm not sure if there's a better way to accomplish this but I've thought of modifying the buildFilter function to accept a builder param. I know some people use default modifiers in their entities so it'd be handy for them to apply default modifier and pass it to buildFilter instead of applying modifier later and not being able to filter by computed columns like in the example above.

```javascript
function buildFilter<M extends BaseModel, K extends typeof Model>(
  modelClass: K,
  trx?: Transaction,
  options?: FilterQueryBuilderOptions<M>,
  builder?: QueryBuilder<M>,
)
```

**Comment by efraimrodrigues** [comment]
I've created PR #61 for this.

Another solution that I can think of is to pass `modifiers?: string | string[] | func: (builder: this) => void` as a options property and apply them in the `buildFilter` method.

**Comment by jeff3yan** [comment]
This sounds pretty reasonable, although I prefer your suggestion to have it on the `options` rather than on the main `buildFilter` arguments - to keep it relatively clean.

There's no other way for someone to specify a custom builder, so this looks good.

**Comment by efraimrodrigues** [comment]
@jeff3yan yeah, it makes sense. So which one do you think we should be passing, `modifiers` or `builder`? I'm more inclined towards `builder` object, but I'm fine with any.
