### ISSUE TITLE
Is this compatible with objection latest?

### ISSUE THREAD

**Issue by efraimrodrigues** [tandg-digital/objection-filter#68]
I'm getting the following and I'm wondering if it's still working with objection@latest. If so, can we update it? 
```
npm WARN Could not resolve dependency:
npm WARN peer objection@"^2.1.2" from objection-filter@4.3.1
npm WARN node_modules/objection-filter
npm WARN   objection-filter@"4.3.1" from the root project
```

**Comment by jeff3yan** [comment]
I'm not aware of anything specific breaking, but I'll see if I can find some time this week for some testing and double check compatibility with the newer versions.

**Comment by srcmayte** [comment]
I have had a similar issue, and believe it's because of the peer dependency as set in the package.json here: https://github.com/tandg-digital/objection-filter/blob/master/package.json#L80C9-L80C9

@jeff3yan is Objection ^2.1.2 really a peer dep, considering it works fine with ObjectionJS 3.0+

**Comment by jeff3yan** [comment]
@srcmayte yup makes sense, forgot to update peer dependencies after the v3 update in dev dependencies. I'll update that now and push that out soon.

**Comment by srcmayte** [comment]
> @srcmayte yup makes sense, forgot to update peer dependencies after the v3 update in dev dependencies. I'll update that now and push that out soon.

Superb!

**Comment by jeff3yan** [comment]
This has been updated and pushed to npm now. If there's any problem I'll re-open this issue to track it.
