### ISSUE TITLE
Relationship modifiers don't have access to the root builder's context.

### ISSUE THREAD

**Issue by elby22** [tandg-digital/objection-filter#71]
From PR: #70: 

> Objection allows relations to specify a modifier() in their definition. In some instances, the modifier does not have access to the root builder's context in queries generated by objection-filter. This PR ensures that the modifiers have access to the context in all cases.
> 
> One particular example is with a many-to-many relationship, a new query is created from the model instead of the root builder. I added a failing test case using an eager clause with a many-to-many relationship, and a modifier on that relationship. This modifier conditionally runs if a function is passed to the context.

This only seems to happen in some edge scenarios. The last time that the modifier is invoked during the filter build, the context is available, but not for all invocations. I'm using a modifier which needs the context, and found this issue during development. 

The current PR has a failing test case, but will push the fix after I find any other places we create a new query without adding the context. 
@jeff3yan As a sanity check, are there any circumstances where we _wouldn't_ want the context passed in?

**Comment by jeff3yan** [comment]
It sounds like a reasonable change, I had a quick look through the code base and it doesn't look like there's anywhere that would be affected by having access to the root builder context.

The tests should cover most of the common scenarios, including eager loads - and those already have a separate context from what I remember.

**Comment by elby22** [comment]
@jeff3yan Thanks for the feedback. The new and existing tests pass with the changes in the PR. Would you please take a look and merge when you get a chance?

**Comment by elby22** [comment]
@jeff3yan closing this as the PR is merged. Can you bump the version and release to NPM when you get a chance? Thanks for the help!
