### ISSUE TITLE
Applying to an existing QueryBuilder?

### ISSUE THREAD

**Issue by timhuff** [tandg-digital/objection-filter#9]
Can this be used on an existing query builder? I have a situation where I'm handed one as a parameter and this would work well.

**Comment by jeff3yan** [comment]
This isn't really an appropriate long term solution, but you can take advantage of the lack of public/private instance variables in javascript by doing:
```
const filterQuery = buildFilter(Model);
filterQuery._builder = existingQueryBuilder;
filterQuery.Model = existingQueryBuilder.modelClass();

return await filterQuery.build(request.query.filter);
```
This isn't part of the publicly documented API so it may change in the future, so make sure you have enough tests to catch this specific scenario.

**Comment by timhuff** [comment]
Thanks! I appreciate the heads up on the private API, too. I'll install from a commit to make sure it doesn't change under me.
